version: '3'

services:
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    restart: always

  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - todoback
    restart: always

  todotests:
    image: todotests
    depends_on:
      - todoback
      - todofront
    network_mode: host
    restart: always
